### ISSUE TITLE
Profileditor

### ISSUE THREAD

**Issue by stefanbente** [Archi-Lab/ptb-web-client#29]

**Comment by stefanbente** [comment]
Autorisierung machen wir gesammelt später. Idee: 
* Angucken jeder
* Bearbeiten nur Person selbst

**Comment by jlengelsen** [comment]
Issue moved to [Archi-Lab/prox-backlog #154](https://github.com/Archi-Lab/prox-backlog/issues/154) via [**ZenHub**](https://www.zenhub.com/)
