### ISSUE TITLE
Lauffähigkeit am GPPD garantieren

### ISSUE THREAD

**Issue by stefanbente** [Archi-Lab/ptb-web-client#40]

**Comment by rudolfgrauberger** [comment]
Ich habe beim Testen der Live-Version festsgellt, dass nicht authentifizierte Websiten-Besucher sich zwar die Projekte in der Übersicht anschaufen können, diese aber über **Details** nicht aufrufen können.

Die Seite bleibt weiß, allerdings erhält man in der Developer-Console die nachfolgende Fehlermeldung:
`Failed to load resource: the server responded with a status of 401 ()`

Nach kurzer Analyse stellte ich fest, dass bei dem Refactoring und der Integration des `gp-ss2019` in den `master`, eine Policy nicht übernommen wurde. Ich habe es zuerst im `dev` branch gefixt (https://github.com/Archi-Lab/prox-project-service/commit/b783930982a80a670802114d4cc6caf166fb541f). Das Mergen in den Master will ich morgen mit @jlengelsen machen.
