### ISSUE TITLE
Session-Timeout mitten in der Eingabe eines Projekts

### ISSUE THREAD

**Issue by stefanbente** [Archi-Lab/ptb-web-client#45]
... sehr nervig, war gerade mitten im Editieren, und dann kam nach dem Speichern direkt der Login-Screen. Projekt war dann auch nicht gespeichert. 

Idle-Time war gar nicht so lange nach der letzten Aktion, höchstens 2-3 min.

=> sollte noch einmal mit der Zeit von 2-3 min getestet werden.

**Comment by xLacrima** [comment]
Daten im Projekteditor werden alle 5 Sekunden gespeichert.
Der Abrechen Button löscht die Daten.
Funktion nur für neue Projekte aktiviert.
(:
